spring:
  cloud:
    gateway:
      routes:
        - id: foo_route
          uri: https://foo.org
          predicates:
            - Host=foo.org
application:
  proxy:
    auth-header-name: X-CUSTOMIZE-HEADER
